### ISSUE TITLE
custom build command for `openssl-sys v0.9.71`

### ISSUE THREAD

**Issue by TheBlindM** [chipsenkbeil/distant#224]
os：win10

Openssl has already been installed on this machine. Both ssh rs and wezterm ssh can compile normally.
But 'termwiz=' 0.20.0 'doesn't work

**Comment by chipsenkbeil** [comment]
You're saying that termwiz 0.20.0 won't compile on Windows 10? It should compile to my knowledge, and the [readme for that project explicitly calls out Windows 10](https://github.com/wez/wezterm/blob/419210bc1499e46ff7c45dbdacba3474aff67cd3/termwiz/README.md?plain=1#L36-L40).

What error are you getting when compiling it yourself? Is there a reason that the pre-built binary for Windows won't work for you?

**Comment by TheBlindM** [comment]
> You're saying that termwiz 0.20.0 won't compile on Windows 10? It should compile to my knowledge, and the [readme for that project explicitly calls out Windows 10](https://github.com/wez/wezterm/blob/419210bc1499e46ff7c45dbdacba3474aff67cd3/termwiz/README.md?plain=1#L36-L40).
> 
> What error are you getting when compiling it yourself? Is there a reason that the pre-built binary for Windows won't work for you?

The following error was encountered when introducing 'distance ssh2="0.20"' in cargo. toml

```
C:/Users/10431/.cargo/bin/cargo.exe check --message-format json --workspace --all-targets -Z unstable-options --keep-going
    Checking cfg-if v1.0.0
    Checking value-bag v1.4.1
    Checking winapi v0.3.9
    Checking windows_x86_64_msvc v0.48.0
    Checking memchr v2.5.0
    Checking smallvec v1.11.0
    Checking scopeguard v1.1.0
    Checking pin-project-lite v0.2.10
    Checking num-traits v0.2.15
    Checking once_cell v1.18.0
    Checking futures-core v0.3.28
    Checking libc v0.2.147
    Checking serde v1.0.167
    Checking bitflags v1.3.2
    Checking zeroize v1.6.0
    Checking futures-io v0.3.28
    Checking getrandom v0.2.10
    Checking crossbeam-utils v0.8.16
    Checking windows-targets v0.48.1
    Checking thiserror v1.0.43
    Checking itoa v1.0.8
    Checking typenum v1.16.0
    Checking lock_api v0.4.10
    Checking ryu v1.0.14
    Checking byteorder v1.4.3
    Checking socket2 v0.4.9
    Checking slab v0.4.8
    Checking bytes v1.4.0
    Checking log v0.4.19
    Checking event-listener v2.5.3
    Checking num_cpus v1.16.0
    Checking num-integer v0.1.45
    Checking rand_core v0.6.4
    Checking instant v0.1.12
    Checking windows-sys v0.48.0
    Checking parking_lot_core v0.9.8
    Checking futures-sink v0.3.28
    Checking generic-array v0.14.7
    Checking tinyvec_macros v0.1.1
    Checking serde_json v1.0.100
    Checking lazy_static v1.4.0
    Checking pin-utils v0.1.0
    Checking uuid v1.4.0
    Checking futures-task v0.3.28
    Checking siphasher v0.3.10
    Checking subtle v2.5.0
    Checking unicode-bidi v0.3.13
    Checking percent-encoding v2.3.0
    Checking aho-corasick v1.0.2
    Checking untrusted v0.7.1
    Checking mio v0.8.8
    Checking parking_lot v0.12.1
    Checking futures-channel v0.3.28
    Checking crypto-common v0.1.6
    Checking tinyvec v1.6.0
    Checking regex-syntax v0.7.3
    Checking fastrand v1.9.0
    Checking spin v0.5.2
    Checking parking_lot_core v0.8.6
    Checking concurrent-queue v2.2.0
    Checking const-oid v0.9.4
    Checking time v0.1.45
    Checking waker-fn v1.1.0
    Checking form_urlencoded v1.2.0
    Checking parking v2.1.0
    Checking hashbrown v0.12.3
    Checking num-bigint v0.4.3
    Checking tokio v1.29.1
    Checking futures-util v0.3.28
    Checking async-lock v2.7.0
    Checking unicode-normalization v0.1.22
    Checking regex-automata v0.3.0
    Checking ahash v0.8.3
    Checking ring v0.16.20
    Checking parking_lot v0.11.2
    Checking time-core v0.1.1
    Checking allocator-api2 v0.2.15
    Checking chrono v0.4.26
    Checking hex v0.4.3
    Checking arrayvec v0.7.3
    Checking futures-lite v1.13.0
    Checking indexmap v1.9.3
    Checking bigdecimal v0.3.1
    Checking async-task v4.4.0
    Checking futures-executor v0.3.28
    Checking async-channel v1.9.0
    Checking idna v0.4.0
    Checking regex v1.9.0
    Checking block-buffer v0.10.4
    Checking webpki v0.22.0
    Checking sct v0.7.0
    Checking time v0.3.22
    Checking hashbrown v0.14.0
    Checking either v1.8.1
    Checking atomic-waker v1.1.1
    Checking rust_decimal v1.30.0
    Checking minimal-lexical v0.2.1
    Checking regex-syntax v0.6.29
    Checking fnv v1.0.7
    Checking base64 v0.21.2
    Checking futures v0.3.28
    Checking io-lifetimes v1.0.11
    Checking url v2.4.0
    Checking pin-project v1.1.2
    Checking digest v0.10.7
    Checking errno v0.3.1
    Checking rustls v0.20.8
    Checking spin v0.9.8
    Checking dotenvy v0.15.7
    Checking itertools v0.10.5
    Checking blocking v1.3.1
    Checking base64ct v1.6.0
    Checking nom v7.1.3
    Checking regex-automata v0.1.10
    Checking unicode_categories v0.1.1
    Checking rustls-pemfile v1.0.3
    Checking sea-query v0.28.5
    Checking hashlink v0.8.3
    Checking webpki-roots v0.22.6
    Checking polling v2.8.0
    Checking futures-intrusive v0.4.2
    Checking rustix v0.37.23
    Checking tokio-rustls v0.23.4
    Checking flume v0.10.14
    Checking stringprep v0.1.2
    Checking tokio-stream v0.1.14
    Checking libsqlite3-sys v0.24.2
    Checking pem-rfc7468 v0.7.0
    Checking ahash v0.7.6
    Checking crossbeam-queue v0.3.8
    Checking sqlformat v0.2.1
    Checking tracing-core v0.1.31
    Checking atoi v1.0.0
   Compiling openssl-sys v0.9.71
    Checking phf_shared v0.10.0
    Checking phf_shared v0.8.0
    Checking winapi-util v0.1.5
    Checking async-io v1.13.0
    Checking sqlx-rt v0.6.3
    Checking cpufeatures v0.2.9
    Checking new_debug_unreachable v1.0.4
    Checking hmac v0.12.1
    Checking async-executor v1.5.1
    Checking der v0.7.7
    Checking windows_x86_64_msvc v0.39.0
    Checking thread_local v1.1.7
    Checking aliasable v0.1.3
    Checking tracing v0.1.37
    Checking mac v0.1.1
    Checking precomputed-hash v0.1.1
    Checking phf v0.8.0
    Checking same-file v1.0.6
    Checking async-stream v0.3.5
    Checking sqlx-core v0.6.3
    Checking sea-strum v0.23.0
    Checking semver v1.0.17
    Checking ff v0.13.0
    Checking ppv-lite86 v0.2.17
    Checking spki v0.7.2
    Checking windows v0.39.0
    Checking base16ct v0.2.0
    Checking ouroboros v0.15.6
    Checking utf-8 v0.7.6
    Checking futf v0.1.5
    Checking os_str_bytes v6.5.1
    Checking dtoa v1.0.8
    Checking walkdir v2.3.3
    Checking string_cache v0.8.7
    Checking sqlx v0.6.3
    Checking hkdf v0.12.3
    Checking libz-sys v1.1.12
    Checking group v0.13.0
    Checking rand_chacha v0.3.1
    Checking pkcs8 v0.10.2
    Checking matchers v0.1.0
    Checking anyhow v1.0.71
    Checking crypto-bigint v0.5.2
    Checking sharded-slab v0.1.4
    Checking tendril v0.4.3
    Checking clap_lex v0.2.4
    Checking dtoa-short v0.3.4
    Checking textwrap v0.16.0
    Checking nodrop v0.1.14
    Checking sea-query-binder v0.3.1
    Checking matches v0.1.10
    Checking stable_deref_trait v1.2.0
    Checking alloc-no-stdlib v2.0.4
    Checking raw-window-handle v0.5.2
    Checking sec1 v0.7.3
    Checking itoa v0.4.8
    Checking opaque-debug v0.3.0
    Checking rand v0.8.5
    Checking tracing-subscriber v0.3.17
    Checking markup5ever v0.10.1
    Checking sea-schema v0.11.0
    Checking inout v0.1.3
    Checking clap v3.2.25
    Checking fxhash v0.2.1
    Checking sea-orm v0.11.3
    Checking thin-slice v0.1.1
    Checking servo_arc v0.1.1
    Checking alloc-stdlib v0.2.2
    Checking adler v1.0.2
    Checking elliptic-curve v0.13.5
    Checking cssparser v0.27.2
    Checking webview2-com-sys v0.19.0
    Checking num-rational v0.4.1
    Checking async-global-executor v2.3.1
    Checking html5ever v0.25.2
    Checking rfc6979 v0.4.0
    Checking cipher v0.4.4
    Checking sea-orm-cli v0.11.3
    Checking phf v0.10.1
    Checking signature v2.1.0
    Checking cfb v0.7.3
    Checking crc32fast v1.3.2
    Checking brotli-decompressor v2.3.4
    Checking miniz_oxide v0.7.1
    Checking universal-hash v0.5.1
    Checking selectors v0.22.0
    Checking phf_shared v0.11.2
    Checking treediff v4.0.2
    Checking kv-log-macro v1.0.7
    Checking serial-core v0.4.0
    Checking bytemuck v1.13.1
    Checking unicode-segmentation v1.10.1
    Checking color_quant v1.1.0
    Checking dunce v1.0.4
    Checking ecdsa v0.16.8
    Checking infer v0.12.0
    Checking sea-orm-migration v0.11.3
    Checking brotli v3.3.4
    Checking flate2 v1.0.26
    Checking poly1305 v0.8.0
    Checking kuchiki v0.8.1
    Checking phf v0.11.2
    Checking json-patch v1.0.0
    Checking async-std v1.12.0
    Checking serial-windows v0.4.0
    Checking chacha20 v0.9.1
    Checking webview2-com v0.19.1
    Checking image v0.24.6
    Checking strum v0.24.1
    Checking primeorder v0.13.2
    Checking sha2 v0.10.7
    Checking http v0.2.9
    Checking serde_with v3.0.0
    Checking aead v0.5.2
    Checking rmp v0.8.12
    Checking filedescriptor v0.8.2
    Checking crossbeam-channel v0.5.8
    Checking serde_bytes v0.11.12
    Checking ordered-float v3.7.0
    Checking dirs-sys-next v0.1.2
    Checking const-str v0.5.6
    Checking ucd-trie v0.1.6
    Checking strsim v0.10.0
    Checking glob v0.3.1
    Checking serial v0.4.0
    Checking p256 v0.13.2
    Checking async-process v1.7.0
    Checking async-net v1.7.0
    Checking chacha20poly1305 v0.10.1
    Checking rmp-serde v1.1.2
    Checking async-fs v1.6.0
    Checking tao v0.16.2
    Checking bstr v0.1.4
    Checking distant-auth v0.20.0
    Checking dirs-next v2.0.0
    Checking shared_library v0.1.9
    Checking pest v2.7.2
    Checking wezterm-dynamic v0.1.0
    Checking tauri-utils v1.4.0
    Checking dirs-sys v0.3.7
    Checking bstr v1.6.0
    Checking aho-corasick v0.7.20
    Checking bitflags v2.3.3
    Checking shell-words v1.1.0
    Checking destructure_traitobject v0.2.0
    Checking lab v0.11.0
    Checking dyn-clone v1.0.12
    Checking linked-hash-map v0.5.6
    Checking http-range v0.1.5
    Checking filenamegen v0.2.4
    Checking wry v0.24.3
    Checking semver-parser v0.10.2
    Checking smol v1.3.0
    Checking nom v5.1.3
    Checking dirs v4.0.0
    Checking windows_x86_64_msvc v0.42.2
    Checking globset v0.4.10
    Checking distant-protocol v0.20.0
    Checking portable-pty v0.7.0
    Checking unsafe-any-ors v1.0.0
    Checking csscolorparser v0.6.2
    Checking distant-net v0.20.0
    Checking yaml-rust v0.4.5
    Checking tauri-runtime v0.14.0
    Checking camino v1.1.6
    Checking migration v0.1.0 (D:\study\T-Shell-Plus\src-tauri\migration)
    Checking digest v0.9.0
    Checking block-buffer v0.9.0
    Checking filetime v0.2.21
    Checking ordered-float v2.10.0
    Checking rtoolbox v0.0.1
    Checking deltae v0.3.2
    Checking equivalent v1.0.0
    Checking base64 v0.13.1
    Checking utf8parse v0.2.1
    Checking typemap-ors v1.0.0
    Checking distant-core v0.20.0
    Checking serde_yaml v0.8.26
    Checking tauri-runtime-wry v0.14.0
    Checking serialize-to-javascript v0.1.1
    Checking ignore v0.4.20
    Checking windows-sys v0.42.0
    Checking sha2 v0.9.9
    Checking tar v0.4.38
    Checking serde-value v0.7.0
    Checking rpassword v7.2.0
    Checking wezterm-color-types v0.2.0
    Checking terminfo v0.7.5
    Checking semver v0.11.0
    Checking vtparse v0.6.2
    Checking indexmap v2.0.0
    Checking tempfile v3.6.0
    Checking wezterm-bidi v0.2.2
    Checking async-compat v0.2.1
    Checking thread-id v4.1.0
    Checking encoding_rs v0.8.32
    Checking finl_unicode v1.2.0
    Checking typed-path v0.3.2
    Checking humantime v2.1.0
    Checking unsafe-libyaml v0.2.8
    Checking fixedbitset v0.4.2
    Checking retain_mut v0.1.9
    Checking arc-swap v1.6.0
    Checking log-mdc v0.1.0
    Checking state v0.5.3
    Checking memmem v0.1.1
    Checking async-once-cell v0.5.3
    Checking deadpool-runtime v0.1.2
    Checking winsplit v0.1.0
    Checking window-shadows v0.2.1
    Checking entity v0.1.0 (D:\study\T-Shell-Plus\src-tauri\entity)
    Checking window-vibrancy v0.4.0
    Checking easy-parallel v3.3.0
    Checking serde_yaml v0.9.22
    Checking log4rs v1.2.0
    Checking tauri v1.4.1
    Checking termwiz v0.20.0
    Checking deadpool v0.9.5
error: failed to run custom build command for `openssl-sys v0.9.71`
error: failed to run custom build command for `openssl-sys v0.9.71`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
  process didn't exit successfully: `D:\study\T-Shell-Plus\src-tauri\target\debug\build\openssl-sys-c88042c7336152e2\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=D:\\study\\T-Shell-Plus\\src-tauri\\target\\debug\\build\\openssl-sys-9bc8a7a5976e2b7a\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"
  --- stderr
  thread 'main' panicked at '
  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=D:\\study\\T-Shell-Plus\\src-tauri\\target\\debug\\build\\openssl-sys-9bc8a7a5976e2b7a\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"
      Failed to execute: program not found
      ', C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-300.1.3+3.1.2\src\lib.rs:573:9
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library\std\src\panicking.rs:593
     1: core::panicking::panic_fmt
               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library\core\src\panicking.rs:67
     2: openssl_src::Build::build
     3: openssl_src::Build::build
     4: build_script_main::find_vendored::get_openssl
     5: build_script_main::env::{{closure}}
     6: build_script_main::find_openssl::{{closure}}
     7: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by chipsenkbeil** [comment]
Ah, you need to have perl installed. You can see that in the error message you shared.

```
Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=D:\\study\\T-Shell-Plus\\src-tauri\\target\\debug\\build\\openssl-sys-9bc8a7a5976e2b7a\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"
      Failed to execute: program not found
      ', C:\Users\10431\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-300.1.3+3.1.2\src\lib.rs:573:9
```

**Comment by TheBlindM** [comment]
Okay, thanku,Can 'distance ssh2' achieve async read and write of channels in shell mode?

**Comment by chipsenkbeil** [comment]
Sorry, I don't follow. The library supports asynchronous operations, which include spawning processes in a shell, writing to stdin, and reading stdout. You can continue to do other async operations while a process is running as the process is created using a dedicated channel, and other asynchronous operations happen in other channels.

**Comment by TheBlindM** [comment]
> Sorry, I don't follow. The library supports asynchronous operations, which include spawning processes in a shell, writing to stdin, and reading stdout. You can continue to do other async operations while a process is running as the process is created using a dedicated channel, and other asynchronous operations happen in other channels.

Perhaps the translation software did not translate accurately, thank you anyway😁
